/* Nicelikler ve Değişimler temasının kısa dersleri. Biçim ve kurallar: ortak/katalog.js başındaki açıklama. */
KATALOG.tema('matematik', 'nicelikler-ve-degisimler', {
  tanitim: 'Bir nicelik değişince öbürü nasıl değişir? En yalın doğrudan, f(x) = x’ten başlayıp doğruları, mutlak değeri ve onlarla kurulan denklemleri grafikte görerek ilerleriz.',
  konular: [
    { harf: 'A', ad: 'Doğrusal fonksiyonlar ve nitel özellikleri', renk: '#6ea8ff', dersler: [
      ['a1-degisen-iki-nicelik.html', 'Değişen iki nicelik', 'Saat ilerledikçe termometredeki sayı değişir; hangisi hangisine bağlıdır?', 4, 203],
      ['a2-girdi-ve-cikti-kumeleri.html', 'Girdi ve çıktı kümeleri', 'Tuş takımında yalnızca 1’den 9’a kadar sayı varsa hangi numaralar girilebilir?', 4, 217],
      ['a3-sifir-ve-isaret.html', 'Sıfır ve işaret: f(x) = x', 'Termometre 0’ın altına düşünce ne değişir?', 4, 201],
      ['a4-artanlik-ve-uc-degerler.html', 'Artanlık ve uç değerler: f(x) = x', 'Asansör yükseldikçe kat numarası artar; en büyük numara nerede?', 4, 203],
      ['a5-bire-birlik.html', 'Bire birlik: f(x) = x', 'İki öğrenci aynı okul numarasını taşıyabilir mi?', 4, 221],
      ['a6-dogruyu-kaydirmak.html', 'Doğruyu kaydırmak: f(x) + k ve f(x ± r)', 'Otoparkın giriş ücreti 5 lira artarsa ücret grafiği nasıl değişir?', 4, 279],
      ['a7-egimi-belirleyen-a.html', 'Eğimi belirleyen a', 'İki kat hızla giden araç aynı sürede kaç kat yol alır?', 4, 269],
      ['a8-sabit-fonksiyon.html', 'Sabit fonksiyon', 'Sabit ücretli abonelikte kullanım artarsa fatura ne olur?', 4, 266],
      ['a9-katsayilardan-grafigi-okumak.html', 'Katsayılardan grafiği okumak', 'İki kargo firmasının ücret doğruları nerede kesişir?', 4, 275],
      ['a10-katsayi-ve-artanlik.html', 'Katsayı ve artanlık-azalanlık', 'Taksimetre açıldıktan sonra yol uzadıkça ücret düşebilir mi?', 4, 260],
      ['a11-ax-b-nin-isareti.html', 'ax + b’nin işareti', '100 lira her gün 20 lira azalıyorsa hangi gün eksiye düşersin?', 4, 292],
      ['a12-artanligin-ispati.html', 'Artanlığın ispatı', '“Yol uzadıkça ücret azalmaz” sözü her mesafe için nasıl güvenceye alınır?', 4, 266],
      ['a13-bire-birligin-ispati.html', 'Bire birliğin ispatı', 'Her ürüne ayrı barkod verildiği nasıl denetlenir?', 3, 220],
      ['a14-grafik-mi-cebir-mi.html', 'Grafik mi, cebir mi?', 'Bir iddiayı denetlemek için üç örneğe mi bakarsın, kurala mı?', 4, 281],
      ['a15-aralikta-en-buyuk-en-kucuk.html', 'Bir aralıkta en büyük ve en küçük değer', '12 yaşından küçüklere satılan biletin en pahalısı hangi yaşta?', 4, 220],
      ['a16-parcali-gosterim.html', 'Parçalı gösterim', 'Isıtılan buzun sıcaklığı baştan sona aynı hızla mı yükselir?', 4, 215],
      ['a17-tekrar.html', 'Konu tekrarı: Doğrusal fonksiyonlar', 'On altı dersin kuralları aklında mı?', 1, 284],
    ] },
    { harf: 'B', ad: 'Mutlak değer fonksiyonu ve nitel özellikleri', renk: '#3cc8e8', dersler: [
      ['b1-mutlak-deger-ile-x.html', '|x| ile f(x) = x', '3 km doğu ile 3 km batı, evden uzaklık olarak neden aynı sayıdır?', 4, 248],
      ['b2-mutlak-degerin-parcali-gosterimi.html', '|x|’in parçalı gösterimi', 'Hesabında −40 lira varsa borcun kaç liradır?', 4, 243],
      ['b3-mutlak-degerin-nitel-ozellikleri.html', '±|x|’in nitel özellikleri', 'Ev ile okul arasında eve uzaklığın en az olduğu yer neresidir?', 4, 323],
      ['b4-mutlak-degerli-dogrunun-sifiri.html', '|ax + b|’nin sıfırı', 'Asansör 3. kattayken hangi kata gidersen kat farkı sıfır olur?', 4, 300],
      ['b5-c-ile-yukari-asagi.html', 'c ile yukarı aşağı: ±|h(x)| ± c', 'Sapması hiç 0 olmayan makinenin en küçük sapması neye eşittir?', 4, 286],
      ['b6-mutlak-degerli-fonksiyonun-parcali-gosterimi.html', 'Mutlak değerli fonksiyonun parçalı gösterimi', 'Evin iki yanında aynı tarife tek kuralla nasıl yazılır?', 4, 262],
      ['b7-tekrar.html', 'Konu tekrarı: Mutlak değer fonksiyonu', 'Altı dersin kuralları aklında mı?', 1, 286],
    ] },
    { harf: 'C', ad: 'Doğrusal fonksiyonlarla denklem ve eşitsizlik problemleri', renk: '#ff8a5b', dersler: [
      ['c1-problemi-fonksiyona-cevirmek.html', 'Problemi fonksiyona çevirmek', 'Sabit 20 lira artı kilo başına 5 lira: 10 kilonun ücreti nasıl bulunur?', 4, 281],
      ['c2-sifir-ve-isaretle-cozum.html', 'f(x) = 0, f(x) < 0 ve f(x) > 0', '60 litrelik tank dakikada 5 litre boşalıyorsa su ne zaman biter?', 4, 292],
      ['c3-iki-dogrunun-kesisimi.html', 'f(x) = g(x): iki doğrunun kesişimi', 'Satıcının ve alıcının anlaştığı fiyat nasıl bulunur?', 4, 241],
      ['c4-hangi-dogru-ustte.html', 'f(x) ≤ g(x) ve f(x) ≥ g(x)', 'İki kargo firmasından hangisi kaç kilodan sonra daha ucuz?', 4, 262],
      ['c5-mutlak-deger-esittir-k.html', '|f(x)| = k', '500 gramlık paket tam 10 gram sapıyorsa kaç gram olabilir?', 4, 256],
      ['c6-mutlak-deger-esitsizlikleri.html', '|f(x)| < k ve |f(x)| > k', 'Sıcaklık 4 °C’den 2 dereceden az sapmalıysa hangi sıcaklıklar uygun?', 4, 315],
      ['c7-mutlak-deger-esittir-dogru.html', '|f(x)| = g(x)', 'İki kurye hangi mesafede aynı ücreti ister?', 4, 293],
      ['c8-mutlak-deger-ile-dogru-esitsizligi.html', '|f(x)| ≤ g(x) ve |f(x)| ≥ g(x)', 'Hangi mesafelerde birinci kuryenin ücreti ikincisinden fazla olmaz?', 4, 322],
      ['c9-cozumu-baska-yoldan-sinamak.html', 'Çözümü başka yoldan sınamak', 'Aynı hesabı iki farklı yoldan yapıp aynı sonucu bulmak ne söyler?', 4, 310],
      ['c10-modelin-siniri.html', 'Modelin sınırı', 'Göl her gün 2 cm çekiliyorsa bu kural 200 gün sonra da geçerli mi?', 4, 300],
      ['c11-tekrar.html', 'Konu tekrarı: Denklem ve eşitsizlik problemleri', 'On dersin kuralları aklında mı?', 1, 310],
    ] },
  ],
});
